server:
  port: 8080
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

spring:
  application:
    name: capstone
  #profiles:
    #active: local

  # 1. Database (MySQL)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/capstone_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  # 2. JPA
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect

  # 3. Redis
  data:
    redis:
      host: redis #${REDIS_HOST}
      port: 6379 #${REDIS_PORT:6379}
      # password: ${REDIS_PASSWORD}

  # 5. File Upload (Multipart)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # 6. AWS S3 (Spring Cloud AWS)
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: ${S3_BUCKET_NAME}


# 8. Custom JWT Config
jwt:
  secret:  ${JWT_SECRET}
  access-token-validity: 3600000 #1시간
  refresh-token-validity: 1209600000 #14일

# 9. Logging
logging:
  level:
    root: INFO
    org.sopt: DEBUG

# 10. Open Ai
openai:
  api-key: ${OPENAI_API_KEY}
  url: ${OPENAI_URL}
  model: ${OPENAI_MODEL}

# 11. Python Model
emotion:
  api:
    url: ${EMOTION_API_URL:http://127.0.0.1:8000/predict}